name: gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Deploy Flutter web app to github pages
        uses: erickzanardo/flutter-gh-pages@v6
        with:
          webRenderer: html
          targetBranch: main

